name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:

  codechecks:
    name: Code Checks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        toolchain: [stable, beta, nightly]
        include:
        - os: macos-latest
          FEATURES: metal
          RUSTC_WRAPPER: /usr/local/bin/sccache
          SCCACHE_DIR: ~/.sccache
        - os: windows-latest
          FEATURES: vulkan
        - os: ubuntu-latest
          FEATURES: vulkan
          RUSTC_WRAPPER: ~/.bin/sccache
          SCCACHE_DIR: ~/.sccache

    steps:
      - uses: actions/checkout@v2

      - name: install linux deps
# URL for sccache obtained from https://github.com/rust-lang/rust/blob/a4dd850720369d9e5b9df91820b23cddb2badc06/src/ci/docker/scripts/sccache.sh
        run: |
          sudo apt update
          sudo apt install gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev
          mkdir ~/.bin
          curl -fo ~/.bin/sccache https://ci-mirrors.rust-lang.org/rustc/2018-04-02-sccache-x86_64-unknown-linux-musl
          chmod +x ~/.bin/sccache
        if: contains(matrix.os, 'ubuntu')

      - name: install macos deps
        run: |
          brew install sccache
        if: contains(matrix.os, 'macOS')

      - name: install ${{ matrix.toolchain }} toolchain
        id: install-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          # Don't use a 'components:' entry--we don't need them with beta/nightly, plus nightly often doesn't have them
          override: true

      - name: cache amethyst deps
        uses: actions/cache@v2
        with:
          path: ~/.sccache
          key: ${{  runner.os  }}-sccache-${{ steps.install-toolchain.rustc-hash }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-sccache-${{ steps.install-toolchain.rustc-hash }}-

      - name: install rustfmt+clippy on stable
        run: |
          rustup component add rustfmt
          rustup component add clippy
        if: contains(matrix.toolchain, 'stable')

      - name: run rustfmt on stable
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
        if: contains(matrix.toolchain, 'stable')

      - name: run clippy on stable
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features=${{matrix.FEATURES}}
        if: contains(matrix.toolchain, 'stable')

      - name: run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=${{matrix.FEATURES}}